### ISSUE TITLE
Should posX and posY of elements be renamed?

### ISSUE THREAD

**Issue by RobRoseKnows** [chemistry/chemical-libraries#2]
`posX` and `posY` aren't really accurate as it looks like `posX` represents period, and `posY` represents group, which aren't really in the X and Y directions. I would recommend renaming them to `period` and `group` respectively. Obviously this would have to be done in a major version upgrade but I think it'd probably be worthwhile.

**Comment by vreshch** [comment]
The name of field is correct, it’s not period of the element, rather position in grid for Periodic table Table Display. This data is used to display  Periodic table in Molecule editor in https://crystallography.io/  The periodic table will be open source soon as well
Plz take a look:  
![periodic_table](https://user-images.githubusercontent.com/9742863/54756812-a4776380-4bf1-11e9-8497-193db804d159.png)
